name: HT's Comprehend Measures - Release Config

env:
  project_url: "https://github.com/${{github.repository}}"
  latest_manifest_url: "https://github.com/${{github.repository}}/releases/latest/download/module.json"
  release_module_url: "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip"
  changelog_module_url: "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/CHANGELOG.md"

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Version From Tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Adjust manifest
        uses: TomaszKandula/variable-substitution@v1.0.2
        with:
          files: "module.json"
        env:
          version: ${{steps.get_version.outputs.version-without-v}}
          url: ${{ env.project_url }}
          manifest: ${{ env.latest_manifest_url }}
          download: ${{ env.release_module_url }}
          changelog: ${{ env.changelog_module_url }}

      - name: Create Module Archive
        run: |
          zip                                    \
            --recurse-paths                      \
             ./module.zip                        \
            module.json                          \
            module.mjs                           \
            README.md                            \
            LICENSE.txt                          \
            module/                              \
            lang/

      - name: Update Release With Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.unpublished }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json, ./module.zip, ./CHANGELOG.md"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
